#!/bin/bash
case $1 in 
# go to
home)
cd "$HOME"
;;
downloads)
cd ~/Downloads
;;
# misc
cow)
uwusay
;;
system)
hyfetch
;;
say)
echo $2
;;
bark)
echo "the existence of weed and edibles throws into haywire the question of marriage not being eternal because you chose to embark on it in life - iharen"
;;
meow)
echo "erm... this isnt working, im going toswitch back to arch"
;;
credits)
echo "https://ko-fi.com/ermcookie
discord:co.ok.ie"
;;
# package utils
paclist)
sudo pacman --query
;;
pacinstall)
sudo pacman -S $2
;;
pacremove)
sudo pacman -Rns $2
;;
pacconfig)
sudo nano /etc/pacman.conf
;;
sysupdate)
sudo pacman -Syu
;;
aur-config)
mkdir ~/aur
echo "created aur folder"
;;
aur-install)
cd ~/aur
git clone https://aur.archlinux.org/$2.git
cd $2
makepkg -si
;;
#text utils
edit-file)
echo "file editor: "
read editor
echo "file:"
read file
$editor $file
;;
suedit-file)
echo "file editor: "
read editor
echo "file:"
read file
sudo $editor $file
;;
copy)
echo "source: "
read file1
echo "destination: "
read file2
cp $file1 $file2
echo "file copied! :3"
;;
sucopy)
echo "source: "
read file1
echo "destination: "
read file2
sudo cp $file1 $file2
echo "file copied! :3"
;;
esac
$SHELL